/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guipractice;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ashley
 */
public class NewDialog extends java.awt.Dialog {

    /**
     * Creates new form NewDialog
     */
    public NewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            jTextField1.setText("Hi");
            ArrayList<String> groupNames;
            groupNames = new ArrayList<String>();
            String URL = "jdbc:vertica://Vertsyn.duckdns.org:5433/USF_Syniverse_Student";
            Connection conn = DriverManager.getConnection(URL);
            String query = "select * from \"public\".knowledge_base_test where mcc=310 and mnc = 410"; 
            PreparedStatement stm = conn.prepareStatement(query);
            
            try (ResultSet rs = stm.executeQuery(query)) {
                while (rs.next()) { 
                    String groupName = rs.getString("group_name"); 
                        // add group names to the array list
                    groupNames.add(groupName);
                } 
            } 

            // Populate the combo box
            //DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
            //comboBox.setModel(model);
            String[] itemArray = new String[groupNames.size()];
            String[] returnedArray = groupNames.toArray(itemArray);
        


            for (int i = 0; i < returnedArray.length; i++){

                jComboBox1.addItem(returnedArray[i]);
        
            }
        } catch (SQLException ex) {
            Logger.getLogger(NewDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTextField1.setText("jTextField1");
        add(jTextField1, java.awt.BorderLayout.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewDialog dialog = new NewDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
